server:
  port: 8001

## spring jdbc配置
spring:
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: 30
        max-idle: 8
        min-idle: 0
    #host: 39.105.165.90
    #port: 6379
    #password: liu_QUSHI_3-22=-19
    host: 127.0.0.1
    port: 6379
    password: taoge
    #host: 111.229.169.170
   # password: 123456
    #port: 6379
  freemarker:
    template-loader-path: classpath:/template/
    suffix: .ftl
    charset: utf-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/education?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: S8kk6gHV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 6000
  ## 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
lbs:
  key: MYOBZ-OOEW3-KYC3G-YWDXA-DMQJ6-SPBMH
## 虚拟文件上传路径
file:
  uploadPath: /root/uploads/
ueditor:
  configFileName: config.json
# 微信公众号配置
weChat:
  appId: wxc5d3bf3c1fbf6d25
  token: education
  appSecret: cf05150f801935391f29d73695f04300

logging:
    file:  /root/jar/education.log
